// Emoji shortcode map - common Discord-style emoji codes
const emojiMap: Record<string, string> = {
  // Smileys & People
  'smile': '😊',
  'grin': '😁',
  'grinning': '😀',
  'joy': '😂',
  'rofl': '🤣',
  'smiley': '😃',
  'sweat_smile': '😅',
  'laughing': '😆',
  'satisfied': '😆',
  'wink': '😉',
  'blush': '😊',
  'yum': '😋',
  'sunglasses': '😎',
  'heart_eyes': '😍',
  'kissing_heart': '😘',
  'kissing': '😗',
  'kissing_smiling_eyes': '😙',
  'kissing_closed_eyes': '😚',
  'relaxed': '☺️',
  'slightly_smiling_face': '🙂',
  'hugging': '🤗',
  'thinking': '🤔',
  'neutral_face': '😐',
  'expressionless': '😑',
  'no_mouth': '😶',
  'rolling_eyes': '🙄',
  'smirk': '😏',
  'persevere': '😣',
  'disappointed_relieved': '😥',
  'open_mouth': '😮',
  'zipper_mouth': '🤐',
  'hushed': '😯',
  'sleepy': '😪',
  'tired_face': '😫',
  'sleeping': '😴',
  'relieved': '😌',
  'nerd': '🤓',
  'stuck_out_tongue': '😛',
  'stuck_out_tongue_winking_eye': '😜',
  'stuck_out_tongue_closed_eyes': '😝',
  'drooling_face': '🤤',
  'unamused': '😒',
  'sweat': '😓',
  'pensive': '😔',
  'confused': '😕',
  'upside_down': '🙃',
  'money_mouth': '🤑',
  'astonished': '😲',
  'frowning': '☹️',
  'slightly_frowning_face': '🙁',
  'confounded': '😖',
  'disappointed': '😞',
  'worried': '😟',
  'triumph': '😤',
  'cry': '😢',
  'sob': '😭',
  'frowning2': '😦',
  'anguished': '😧',
  'fearful': '😨',
  'weary': '😩',
  'exploding_head': '🤯',
  'grimacing': '😬',
  'cold_sweat': '😰',
  'scream': '😱',
  'flushed': '😳',
  'zany_face': '🤪',
  'dizzy_face': '😵',
  'rage': '😡',
  'angry': '😠',
  'innocent': '😇',
  'cowboy': '🤠',
  'clown': '🤡',
  'lying_face': '🤥',
  'shush': '🤫',
  'symbols_over_mouth': '🤬',
  'face_with_hand_over_mouth': '🤭',
  'face_vomiting': '🤮',
  'hot_face': '🥵',
  'cold_face': '🥶',
  'partying_face': '🥳',
  'woozy_face': '🥴',
  'pleading_face': '🥺',
  'skull': '💀',
  'skull_crossbones': '☠️',
  'poop': '💩',
  'ghost': '👻',
  'alien': '👽',
  'robot': '🤖',
  'smiling_imp': '😈',
  'imp': '👿',
  'japanese_ogre': '👹',
  'japanese_goblin': '👺',
  'see_no_evil': '🙈',
  'hear_no_evil': '🙉',
  'speak_no_evil': '🙊',
  'kiss': '💋',
  'love_letter': '💌',
  'cupid': '💘',
  'gift_heart': '💝',
  'sparkling_heart': '💖',
  'heartpulse': '💗',
  'heartbeat': '💓',
  'revolving_hearts': '💞',
  'two_hearts': '💕',
  'heart_decoration': '💟',
  'broken_heart': '💔',
  'heart': '❤️',
  'orange_heart': '🧡',
  'yellow_heart': '💛',
  'green_heart': '💚',
  'blue_heart': '💙',
  'purple_heart': '💜',
  'black_heart': '🖤',
  'white_heart': '🤍',
  'brown_heart': '🤎',
  
  // Hand gestures
  'wave': '👋',
  'raised_back_of_hand': '🤚',
  'raised_hand': '✋',
  'hand_splayed': '🖐️',
  'vulcan': '🖖',
  'ok_hand': '👌',
  'pinching_hand': '🤏',
  'v': '✌️',
  'crossed_fingers': '🤞',
  'love_you_gesture': '🤟',
  'metal': '🤘',
  'call_me': '🤙',
  'point_left': '👈',
  'point_right': '👉',
  'point_up_2': '👆',
  'middle_finger': '🖕',
  'point_down': '👇',
  'point_up': '☝️',
  'thumbsup': '👍',
  'thumbup': '👍',
  '+1': '👍',
  'thumbsdown': '👎',
  'thumbdown': '👎',
  '-1': '👎',
  'fist': '✊',
  'punch': '👊',
  'left_facing_fist': '🤛',
  'right_facing_fist': '🤜',
  'clap': '👏',
  'raised_hands': '🙌',
  'open_hands': '👐',
  'palms_up_together': '🤲',
  'handshake': '🤝',
  'pray': '🙏',
  'muscle': '💪',
  'leg': '🦵',
  'foot': '🦶',
  'ear': '👂',
  'nose': '👃',
  'brain': '🧠',
  'eyes': '👀',
  'eye': '👁️',
  'tongue': '👅',
  'lips': '👄',
  
  // Other common
  'fire': '🔥',
  'sparkles': '✨',
  'star': '⭐',
  'star2': '🌟',
  'zap': '⚡',
  'boom': '💥',
  'collision': '💥',
  'sweat_drops': '💦',
  'dash': '💨',
  'hole': '🕳️',
  'bomb': '💣',
  'speech_balloon': '💬',
  'thought_balloon': '💭',
  'zzz': '💤',
  '100': '💯',
  'money_with_wings': '💸',
  'moneybag': '💰',
  'gem': '💎',
  'crown': '👑',
  'trophy': '🏆',
  'medal': '🏅',
  'first_place': '🥇',
  'second_place': '🥈',
  'third_place': '🥉',
  'soccer': '⚽',
  'baseball': '⚾',
  'basketball': '🏀',
  'football': '🏈',
  'tennis': '🎾',
  'video_game': '🎮',
  'joystick': '🕹️',
  'headphones': '🎧',
  'microphone': '🎤',
  'guitar': '🎸',
  'musical_note': '🎵',
  'notes': '🎶',
  'pizza': '🍕',
  'hamburger': '🍔',
  'fries': '🍟',
  'hotdog': '🌭',
  'taco': '🌮',
  'burrito': '🌯',
  'popcorn': '🍿',
  'icecream': '🍨',
  'doughnut': '🍩',
  'cookie': '🍪',
  'cake': '🎂',
  'coffee': '☕',
  'tea': '🍵',
  'beer': '🍺',
  'beers': '🍻',
  'wine_glass': '🍷',
  'cocktail': '🍸',
  'rainbow': '🌈',
  'sun': '☀️',
  'moon': '🌙',
  'cloud': '☁️',
  'rain': '🌧️',
  'snow': '❄️',
  'snowflake': '❄️',
  'umbrella': '☂️',
  'sunny': '🌞',
  'dog': '🐕',
  'cat': '🐈',
  'mouse': '🐁',
  'rabbit': '🐇',
  'fox': '🦊',
  'bear': '🐻',
  'panda': '🐼',
  'koala': '🐨',
  'tiger': '🐯',
  'lion': '🦁',
  'cow': '🐄',
  'pig': '🐷',
  'chicken': '🐔',
  'penguin': '🐧',
  'bird': '🐦',
  'eagle': '🦅',
  'duck': '🦆',
  'owl': '🦉',
  'butterfly': '🦋',
  'snail': '🐌',
  'bug': '🐛',
  'ant': '🐜',
  'bee': '🐝',
  'spider': '🕷️',
  'snake': '🐍',
  'turtle': '🐢',
  'fish': '🐟',
  'dolphin': '🐬',
  'whale': '🐳',
  'shark': '🦈',
  'octopus': '🐙',
  'crab': '🦀',
  'rose': '🌹',
  'tulip': '🌷',
  'sunflower': '🌻',
  'cherry_blossom': '🌸',
  'four_leaf_clover': '🍀',
  'christmas_tree': '🎄',
  'gift': '🎁',
  'balloon': '🎈',
  'tada': '🎉',
  'confetti_ball': '🎊',
  'sparkler': '🎇',
  'fireworks': '🎆',
  'rocket': '🚀',
  'airplane': '✈️',
  'helicopter': '🚁',
  'car': '🚗',
  'taxi': '🚕',
  'bus': '🚌',
  'ambulance': '🚑',
  'fire_engine': '🚒',
  'police_car': '🚓',
  'bike': '🚲',
  'ship': '🚢',
  'anchor': '⚓',
  'warning': '⚠️',
  'construction': '🚧',
  'no_entry': '⛔',
  'stop_sign': '🛑',
  'checkered_flag': '🏁',
  'triangular_flag': '🚩',
  'crossed_flags': '🎌',
  'white_flag': '🏳️',
  'rainbow_flag': '🏳️‍🌈',
  'pirate_flag': '🏴‍☠️',
  'check': '✅',
  'white_check_mark': '✅',
  'x': '❌',
  'cross_mark': '❌',
  'question': '❓',
  'exclamation': '❗',
  'interrobang': '⁉️',
  'heart_exclamation': '❣️',
  'copyright': '©️',
  'registered': '®️',
  'tm': '™️',
  'hash': '#️⃣',
  'asterisk': '*️⃣',
  'zero': '0️⃣',
  'one': '1️⃣',
  'two': '2️⃣',
  'three': '3️⃣',
  'four': '4️⃣',
  'five': '5️⃣',
  'six': '6️⃣',
  'seven': '7️⃣',
  'eight': '8️⃣',
  'nine': '9️⃣',
  'keycap_ten': '🔟',
  'abc': '🔤',
  'abcd': '🔡',
  'capital_abcd': '🔠',
  'symbols': '🔣',
  'information_source': 'ℹ️',
  'sos': '🆘',
  'new': '🆕',
  'free': '🆓',
  'up': '🆙',
  'cool': '🆒',
  'ok': '🆗',
  'ng': '🆖',
  'gg': '🇬🇬',
  'lol': '😂',
  'lmao': '🤣',
  'bruh': '😐',
  'cap': '🧢',
  'no_cap': '🚫🧢',
  'sus': '🤨',
  'rip': '🪦',
  'W': '🇼',
  'L': '🇱',
  'goat': '🐐',
  'GOAT': '🐐',
  'nerd_face': '🤓',
  'moyai': '🗿',
  'moai': '🗿',
  'vine_boom': '🗿',
  'sob_face': '😭',
  'dead': '💀',
  'ded': '💀',
  'lit': '🔥',
  'based': '🗿',
  'cringe': '😬',
  'cap_emoji': '🧢',
  'ratio': '📉',
  'salute': '🫡',
  'melting_face': '🫠',
  'dotted_line_face': '🫥',
  'shaking_face': '🫨',
  'peeking_eye': '🫣',
  'face_with_open_eyes_and_hand_over_mouth': '🫢',
  'face_with_diagonal_mouth': '🫤',
  'face_holding_back_tears': '🥹',
  'righteous_anger': '🫠',
};

// Parse :emoji: codes in text and replace with actual emojis
export function parseEmojis(text: string): string {
  return text.replace(/:([a-zA-Z0-9_+-]+):/g, (match, code) => {
    const emoji = emojiMap[code.toLowerCase()];
    return emoji || match; // Return original if not found
  });
}

// Get list of matching emojis for autocomplete
export function getEmojiSuggestions(query: string, limit: number = 10): Array<{ code: string; emoji: string }> {
  const lowerQuery = query.toLowerCase();
  const matches: Array<{ code: string; emoji: string }> = [];
  
  for (const [code, emoji] of Object.entries(emojiMap)) {
    if (code.includes(lowerQuery)) {
      matches.push({ code, emoji });
      if (matches.length >= limit) break;
    }
  }
  
  return matches;
}

// Check if text contains GIF URL
export function isGifUrl(text: string): boolean {
  return text.startsWith('[GIF]') && text.includes('tenor.com');
}

// Extract GIF URL from message
export function extractGifUrl(text: string): string | null {
  const match = text.match(/\[GIF]\((https:\/\/[^)]+)\)/);
  return match ? match[1] : null;
}
