project_id = "pgqlruiivbpsqxikagdn"

[functions.music-api]
verify_jwt = false

[functions.upload-music]
verify_jwt = false

[functions.tenor-gifs]
verify_jwt = false

[functions.refetch-covers]
verify_jwt = false

[functions.web-proxy]
verify_jwt = false
